### ISSUE TITLE
EEPROM is not cleared when reset button is clicked.

### ISSUE THREAD

**Issue by xoan** [escornabot/arduino#2]
The last executed program remains always in memory.

1. Program some movements 
2. Click `go`
3. Click `reset`
4. Power off the Arduino
5. Power on the Arduino
6. Click `go` (or program some movements and click `go`)

The program in 1 is executed before the program in 6.

**Comment by rafacouto** [comment]
Yes, it is the proposed behaviour according to requirements. The program of moves is saved in the EEPROM when it is confirmed with the "Go!" button.

May be this issue is related to #1 (solved at the moment), isn't it?

**Comment by rafacouto** [comment]
No answer: it shoul be...
