### ISSUE TITLE
Include default steps for "brivoi" in beta version

### ISSUE THREAD

**Issue by procastino** [escornabot/arduino#4]
I think the steps for turning and advancing should be set to 90º turn and 10 cm. advance on the brivoi version:
STEPPERS_TURN_STEPS 1024
STEPPERS_LINE_STEPS 1762

**Comment by rafacouto** [comment]
In branch "brivoi", commit c1cbc9a0dccc2a022562fafe5cd94ffe5c72a15e conflicts in _line step_ amount (1738). Please, confirm the right one and we'll proceed with the version tagging for _brivoi_.

**Comment by procastino** [comment]
1738 gives a more precise movement, 1762 gave a little more than 10 cm. Thanks.

**Comment by rafacouto** [comment]
New tag for brivoi released: https://github.com/escornabot/arduino/releases
