### ISSUE TITLE
Configure number of buttons on the keypad

### ISSUE THREAD

**Issue by procastino** [escornabot/arduino#6]
I think it would be possitive to be able to configure the number of buttons of the keypad on the firmware in a simple way, so that anyone could choose the number of buttons best suited for him.

**Comment by rafacouto** [comment]
It is already implemented so you have to assign 0 value to the button is not going to be used (Configuration.h). For example, in order to disconnect the reset button:

```
// input values for each key pressed (0 if key doesn't exist)
#define BS_ANALOG_VALUE_UP 221
#define BS_ANALOG_VALUE_RIGHT 618
#define BS_ANALOG_VALUE_DOWN 518
#define BS_ANALOG_VALUE_LEFT 354
#define BS_ANALOG_VALUE_GO 574
#define BS_ANALOG_VALUE_RESET 0
```
