### ISSUE TITLE
Assign button behavior

### ISSUE THREAD

**Issue by procastino** [escornabot/arduino#7]
Being able to easily assign a behaviour for each button would be a useful improvement.
Some lines to change on the firmware so that anyone with little programming experience could modify how the robot acts when each button is pushed.
Example: Making a game more challenging by changing LEFT and RIGHT (when you push left button, robot moves right and the other way round)

**Comment by rafacouto** [comment]
Two methods are implemented in Bot.cpp to allow changing default behaviors:

[_void Bot::buttonReleased(BUTTON button)_](https://github.com/escornabot/arduino/blob/releases/Escornabot/Bot.cpp#L74)

where actions from BUTTON_\* are associated to code when a key is **normally pressed**; and

[_void Bot::buttonLongReleased(BUTTON button)_](https://github.com/escornabot/arduino/blob/releases/Escornabot/Bot.cpp#L115)

where actions from BUTTON_\* are associated to code when a key is **long pressed**.
